# Generated by Django 4.0.5 on 2022-06-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('badge_num', models.IntegerField(default=0)),
                ('users', models.ManyToManyField(to='main_app.user')),
            ],
        ),
    ]
