# Generated by Django 4.0.4 on 2022-06-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profiles',
        ),
    ]
