# Generated by Django 4.0.4 on 2022-06-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profiles',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_app.profile'),
        ),
    ]
