# Generated by Django 4.0.4 on 2022-06-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_post_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profiles',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main_app.profile'),
        ),
    ]
