# Generated by Django 4.0.4 on 2022-06-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='mary', max_length=80),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posts',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.group'),
        ),
    ]
