# Generated by Django 4.0.4 on 2022-06-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_comment_options_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='mary', max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main_app.profile'),
        ),
    ]
