# Generated by Django 4.0.4 on 2022-06-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_post_name_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='post',
        ),
    ]
