# Generated by Django 4.0.4 on 2022-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_profile_badge_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge_num',
            field=models.IntegerField(default=0),
        ),
    ]
