# Generated by Django 4.0.5 on 2022-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_profile_badge_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='1', max_length=150),
        ),
    ]
