# Generated by Django 4.0.5 on 2022-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='status_img',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToCXRtr20DkXHw0BW6034Mz1JihWvkDhGcPg&usqp=CAU', max_length=500),
        ),
    ]
